---
- name: Add Microsoft Package Repository Key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/keyrings/microsoft.gpg
    state: present

- name: Add Microsoft Package Repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install Microsoft Azure CLI
  apt:
    name: azure-cli
    state: present
    update_cache: yes
