---
# When /usr/local/bin/helm exists, it will not execute the task
- name: Install helm if not exists
  unarchive:
    src: https://get.helm.sh/helm-v3.14.1-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    owner: cloud_user
    group: cloud_user
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm
